### PR TITLE
Added support for custom tagNames for links

### PR DESCRIPTION
**Pull request by swernerx**
This PR adds the capability to define a custom tagName for links. In cases where the `tagName != "a"` we also do not add a `href` attribute anymore. These links are mainly useful for e.g. making full cells clickable but not for having a valid SEO ready link.

### CODE REVIEW

**Comment by faceyspacey** [comment]
Brother it's the same problem. chsck the Travis link and see why it's failing. It has to be using Flow bin 52 not 53 as I wrote yesterday. Then it will pass and I can press merge. In the future don't worry about updating deps. Leave that up to me. There are some quirks and the deps aren't always ready for use.

**Comment by swernerx** [comment]
I know...

**Comment by swernerx** [comment]
The remaining flow errors seem somehow broken as it reports about something in "node_modules". This should be probably excluded.

**Comment by faceyspacey** [comment]
Excellent. Open .flowconfig and ignore it like the others. That's what I did yesterday. It's totally unrelated, typical flow bs.

**Comment by swernerx** [comment]
Done :)

**Comment by faceyspacey** [comment]
excellent!

**Pull request merged**
