### PR TITLE
Render prop function for v2

### PR DESCRIPTION
**Pull request by sibnerian**
Add render prop option that takes in 'active' as a boolean.

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
Can you provide Why. for more than text

**Comment by cdoublev** [comment]
I thought about the why, and now I have some doubts about this feature. They are just thoughts, I could be wrong.

> This will allow easy conditional rendering and will integrate well with many CSS-in-JS technologies !

If it's only meant to set a specific class for when the link in not active, you could use `:not(.activeClass)` in CSS.

> `{ active ? "You're in space now! Whooaaa" : 'Go to space !' }`

If it's meant to change the link content, like "Go back to earth", it feels against progressive enhancement, ie. the user will never see he's in space when JS is disabled in browser, and against [accessibility](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-link-only.html). 

> Best practice is that links with the same destination would have the same descriptions, but links with different purposes and destinations would have different descriptions.

**Comment by sibnerian** [comment]
@ScriptedAlchemy @cdoublev 

Apologies, I'll provide some fresh context -- it's been a while since #91.

From #91:

> This will allow easy conditional rendering and will integrate well with many CSS-in-JS technologies ! :)

CSS in JS is my primary use case for this, and the reason why I forked it in the first place. When you use Aphrodite/Emotion/etc., you conditionally apply styles to an element based on state. So, you need to know the active status to conditionally apply the "active" styles.

Here's a concrete example from my codebase:

```jsx
// Nav.jsx
<NavLink
  to={{ /*whatever */}}
>
  {(active) => <Tab isActive={active} text={tabText[tab]} name={tab} />}
</NavLink>

// Tab.jsx
<label htmlFor={name} {...css(styles.label, isActive && styles.labelActive)}>
{/* contents */}
</label>
```

Without the isActive boolean, I can't apply the correct styles to the `<label>`.

> If it's only meant to set a specific class for when the link in not active, you could use :not(.activeClass) in CSS.

Having a parent with a certain `className` isn't enough -- I'm not writing CSS directly, so I can't use `:not(.activeClassName)` in the selector.

**Comment by sibnerian** [comment]
I mean the point of NavLink is to abstract the idea of checking if the link is active, given current location, and apply a different style. This is just a different way of styling. 

Obviously location’s in the redux state, so it’s possible to implement this separately...but I’d prefer to let the library handle that check.

**Pull request closed without merging**
