### PR TITLE
Use selectLocationState in order to support arbitrary state shapes

### PR DESCRIPTION
**Pull request by iansinnott**
This is the companion PR to: https://github.com/faceyspacey/redux-first-router/pull/37

Please see that PR for full details on this change.

### CODE REVIEW

**Comment by iansinnott** [comment]
Merging this will close #23.

**Comment by faceyspacey** [comment]
Very well done. By the way I didn't notice you properly exported the `selectLocationState` function using an enclosed variable. Well done.

ps. do you mind using `npm run cm` to make commits. If you do, i can just click merge and it will auto-publish. It will also create neatly formatted release logs, etc.

**Comment by iansinnott** [comment]
Thanks. Yeah, I'd be happy to commit with `cm. 

**But**, I wonder if you could incorporate this into a git hook? I see you already use husky. I haven't done anything with commitizen before but ideally they don't require you to run a special command instead of a standard git command. 

I bring this up because I think this will actually be a major issue for contributors if this project really takes off. I don't think there's any way to actually enforce `run cm` unless it is enforced automatically at the command line. People will forget. Hell _**I forgot**_—you already mentioned this to me in the main project.

Something to consider as these projects really take off.

**Comment by faceyspacey** [comment]
there's probably some workaround to achieve it, but i recall it's not straightforward, given all the different things that happens at that point.

**Pull request merged**
