### PR TITLE
fix: use ^ for prop-types dep

### PR DESCRIPTION
**Pull request by hartzis**
use `^` for `prop-types` dep. Helps flatten/clean-up `node_modules` deps

### CODE REVIEW

**Comment by faceyspacey** [comment]
thank you. will add to the next major version.

**Comment by hartzis** [comment]
@ScriptedAlchemy Any chance you have access here to release a patch bump for this simple fix?

**Comment by ScriptedAlchemy** [comment]
Yep! No problem, make sure to tag or DM my handle if there are any requests. I should have write access most faceyspacey repos related to RFR. 

It’s hard to keep track of when PRs come in - if there’s an outstanding one, let me know

**Comment by ScriptedAlchemy** [comment]
I’ll review this tonight

**Comment by ScriptedAlchemy** [comment]
Oh darn. I don't have write access to this one, let me see what I can do

**Comment by ScriptedAlchemy** [comment]
Okay cool, i found my GitHub invite. re running the builds to see id they pass now. then ill see if i can deploy

**Pull request merged**
