### PR TITLE
feat($linkcomponent): Added support for custom component in Link

### PR DESCRIPTION
**Pull request by klis87**
Added `component` prop to `Link`. It allows easy integration with libraries such as `react-bootstrap`:
```javascript
import { NavItem } from 'react-bootstrap';

// ...
<NavLink to="/" component={NavItem} exact>Home</NavLink>
```
It has priority before `a` and `tagName` prop.

### CODE REVIEW

**Comment by klis87** [comment]
For some reason Travis shows 
```
FLOW: Error: dist/Link.js.flow:5
  5: import type { ComponentType } from 'react'
                   ^^^^^^^^^^^^^ Named import from module `react`. This module has no named export called `ComponentType`.
```

I guess this is related to  https://github.com/facebook/flow/issues/4774 .

**Comment by faceyspacey** [comment]
If we r gonna do this let's rename tagName to component and overload it based on whether it received a string to do both.

When making the commit do it as a breaking change.

Make sure the readme explain this.

**Comment by faceyspacey** [comment]
As for the flow error, our flow-bin package etc is not updated to reflect the latest React flow features. Likely it needs to be updated and various new flow errors fixed.

**Comment by klis87** [comment]
I updated `flow-bin` package but it causes even more errors like:
```
Error: dist/handlePress.js.flow:7
  7: export type OnClick = false | ((SyntheticEvent) => ?boolean)
                                     ^^^^^^^^^^^^^^ SyntheticEvent. Application of polymorphic type needs <list of 0-1 arguments>. (Can use `*` for inferrable ones)
```
As I don't use flow myself, it is hard for me to fix that. Do you have time in the near future to do this?

Regarding merging `tagName` and `component` props, I am happy to do it, I will have time tomorrow.

**Comment by klis87** [comment]
@faceyspacey I merged `tagName` and `component` prop, please let me know if there is anything you would like to change.

**Comment by faceyspacey** [comment]
It's looking great. we're just gonna have to fix those Flow errors or people will be getting them in Userland. I'm gonna have to find time to investigate the latest Flow stuff. I'd just fork it and publish it as your own package until then because I may not have time for a week or two. But rest-assured we're gonna have this feature.

**Comment by klis87** [comment]
Great! So I will patiently wait until you fix those Flow errors. Thank you for your help.

**Comment by faceyspacey** [comment]
Thanks for this. This will be in the upcoming Rudy release. Here's the code:

https://github.com/faceyspacey/redux-first-router/blob/rudy-next/src/Link/index.js#L94

...maybe 2 more weeks off :)

**Pull request closed without merging**
