### PR TITLE
Add support for custom tag names

### PR DESCRIPTION
**Pull request by swernerx**
Fixes https://github.com/faceyspacey/redux-first-router-link/issues/34

I did a few cleanups to not pass a non of empty properties further down the React tree. Also simplifies readability of Jest snapshots.

### CODE REVIEW

**Comment by faceyspacey** [comment]
we gotta put the old eslint stuff back to pass (the new airbnb config is notoriously behind the latest eslint releases). here it is to copy paste if it's easier:

```js
{
  "name": "redux-first-router-link",
  "version": "0.0.0-development",
  "description": "a simple but effective <Link /> component for redux-first-router (better for SEO rather than dispatching yourself)",
  "main": "dist/index.js",
  "scripts": {
    "build": "babel src -d dist",
    "build:umd": "BABEL_ENV=commonjs NODE_ENV=development webpack src/Link.js dist/redux-first-router-link.js",
    "build:umd:min": "BABEL_ENV=commonjs NODE_ENV=production webpack src/Link.js dist/redux-first-router-link.min.js",
    "flow-copy": "flow-copy-source src dist",
    "flow-watch": "clear; printf \"\\033[3J\" & npm run flow & fswatch -o ./ | xargs -n1 -I{} sh -c 'clear; printf \"\\033[3J\" && npm run flow'",
    "flow": "flow; test $? -eq 0 -o $? -eq 2",
    "test": "jest",
    "clean": "rimraf dist && mkdir dist",
    "lint": "eslint --fix ./",
    "format": "prettier --single-quote --parser=flow --semi=false --write '{src,__tests__,__test-helpers__}/**/*.js' && npm run lint",
    "precommit": "lint-staged --verbose && npm test",
    "cm": "git-cz",
    "semantic-release": "semantic-release pre && npm publish && semantic-release post",
    "prepublish": "npm run clean && npm run build && npm run flow-copy && npm run build:umd && npm run build:umd:min"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/faceyspacey/redux-first-router-link.git"
  },
  "author": "James Gillmore <james@faceyspacey.com>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/faceyspacey/redux-first-router-link/issues"
  },
  "homepage": "https://github.com/faceyspacey/redux-first-router-link#readme",
  "jest": {
    "verbose": true,
    "moduleFileExtensions": [
      "js"
    ]
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-flow-react-proptypes": "^4.1.0",
    "babel-plugin-transform-flow-strip-types": "^6.22.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "commitizen": "^2.9.6",
    "cz-conventional-changelog": "^2.0.0",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-plugin-flowtype": "^2.32.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-react": "^6.10.3",
    "flow-bin": "^0.53.0",
    "flow-copy-source": "^1.2.0",
    "history": "^4.6.3",
    "husky": "^0.14.3",
    "jest": "^20.0.4",
    "lint-staged": "^4.0.3",
    "prettier": "^1.5.3",
    "react": "^15.x",
    "react-redux": "^5.x",
    "react-test-renderer": "^15.6.1",
    "redux": "^3.x",
    "redux-first-router": "next",
    "rimraf": "^2.6.1",
    "semantic-release": "^7.0.1",
    "travis-github-status": "^1.6.3",
    "webpack": "3.5.5"
  },
  "peerDependencies": {
    "react": "*",
    "react-redux": "*",
    "redux": "*",
    "redux-first-router": "*"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "lint-staged": {
    "*.js": [
      "prettier --single-quote --parser=flow --semi=false --write",
      "eslint --fix",
      "git add"
    ]
  },
  "dependencies": {
    "path-to-regexp": "^1.7.0",
    "prop-types": "15.5.10",
    "rudy-match-path": "^0.1.0"
  }
}

```

**Comment by faceyspacey** [comment]
also in the future, make sure to add me in the top right of this page so i can push commits to the PR.

**Comment by swernerx** [comment]
I don't know about what you mean by "add me in the top right of this page so i can push commits to the PR" because I actually marked the checkbox here:
bildschirmfoto 2017-08-17 um 08 59 50

**Comment by swernerx** [comment]
I chose an alternative approach of updating the eslint config to not throw these compat errors. I think this is the better way: going forward instead backward. ;)

**Comment by swernerx** [comment]
Linting is now successful BTW

**Comment by faceyspacey** [comment]
unfortunately the latest Flow that came out today broke as well:

https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627

**Comment by faceyspacey** [comment]
that is bizarre. i did a force push and it closed the PR. 

...all i did fyi is add "flow-bin": "0.52.0", (i.e. downgrade one version).  

Feel free to open a new PR with that one change and it should pass travis and be done.

**Comment by swernerx** [comment]
That's not very helpful. That one change where multiple changes e.g. also new tests.

**Pull request closed without merging**
